services:
  ethvis:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - eth-labels
    environment:
      - NODE_ENV=production
      - ETH_LABELS=eth-labels:3000
    volumes:
      - node_modules:/app/node_modules

  eth-labels:
    build: "https://github.com/shalajwadhwa/eth-labels.git#main"
    ports:
      - "3000"
    environment:
      - NODE_ENV=production

volumes:
  node_modules: