name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy docker-compose file to server
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yaml ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }}:~/app/
          scp -o StrictHostKeyChecking=no -r .env* ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }}:~/app/ || true
          
      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} '
            mkdir -p ~/app
            cd ~/app
            docker-compose pull
            docker-compose down
            docker-compose up -d
            docker-compose ps
          '