name: Deploy to DigitalOcean Droplet with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Build application
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      # Create a tarball of the build directory
      - name: Create build archive
        run: tar -czf build.tar.gz build/
      
      # Deploy to server
      - name: Copy build to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build.tar.gz,docker-compose.yaml,.env*"
          target: "~/app"
      
      - name: Deploy via SSH to Droplet
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/app
            # Extract the build files
            tar -xzf build.tar.gz
            # Update and restart containers
            docker-compose down
            docker-compose up -d --remove-orphans
