name: Deploy to DigitalOcean

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key manually
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -v -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} 'echo "SSH connection successful"'

      - name: Copy docker-compose and configurations to droplet
        run: |
          scp -i ~/.ssh/id_ed25519 docker-compose.yaml ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }}:~/app/
          scp -i ~/.ssh/id_ed25519 -r .env* ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }}:~/app/ || true

      - name: Deploy with docker-compose
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} '
            cd ~/app && 
            docker-compose pull && 
            docker-compose down && 
            docker-compose up -d
          '

      - name: Verify Deployment
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} '
            cd ~/app && 
            docker-compose ps
          '
